### ISSUE TITLE
Can't install from composer

### ISSUE THREAD

**Issue by vsevolod-kue** [justcoded/wordpress-starter#13]
Hello Justcoded team,
I tried to install the wordpress-starter from composer with the "composer create-project justcoded/wordpress-starter:2.* my-theme" command and got the following issue in the command line "Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package wpackagist-plugin/fakerpress ~0.4.10 exists as wpackagist-plugin/fakerpress[0.5.0, 0.1.0, 0.1.1, 0.1.2, 0.1.3, dev-trunk] but these are rejected by your constraint."

Did I something wrong? I tried to install the starter pack on xampp / windows.

**Comment by aprokopenko** [comment]
Hi, thanks for your report.

Fixed in version 2.0.4
